CREATE DATABASE IF NOT EXISTS todolist;
USE todolist;

CREATE TABLE member (
    ID VARCHAR(50) NOT NULL,
    PWD VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
)

CREATE TABLE roomlist (
    rno INT(10) NOT NULL AUTO_INCREMENT,
    host VARCHAR(200) NOT NULL,
    title VARCHAR(200) NOT NULL,
    PRIMARY KEY (rno),
    CONSTRAINT roomName FOREIGN KEY (host) REFERENCES todolist.member (ID) ON UPDATE NO ACTION ON DELETE NO ACTION
)

CREATE TABLE plan (
    PNO INT(10) NOT NULL AUTO_INCREMENT,
    RNO INT(10) NOT NULL,
    goal VARCHAR(200) NOT NULL,
    achievement TINYINT(1) NOT NULL,
    PRIMARY KEY (PNO),
    CONSTRAINT plan_ibfk_1 FOREIGN KEY (RNO) REFERENCES todolist.roomlist (rno) ON UPDATE NO ACTION ON DELETE NO ACTION
)

CREATE USER 'user'@'localhost' IDENTITY BY 'pass'
GRANT ALL PRIVILEGES ON . TO 'user'@'localhost' WITH GRANT OPTION
CREATE USER 'user'@'%' IDENTITY BY 'pass'
GRANT ALL PRIVILEGES ON . TO 'user'@'%' WITH GRANT OPTION